<?php

return array (
  'name' => '小印象',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'general/profile',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'video' => 'Video',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'upload' => 'Upload',
    'sms' => 'Sms',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'qiniu_access_key' => 'OUahOqyuJIzcOT_ImZl4tfg1MyH2X2mVl8Mwk6GF',
  'qiniu_secret_key' => '_iQedrZ1zSls6Fs0RmX94ZQ6QdAHekivaXO-eHKk',
  'avatar_bucket' => 'testheadimg',
  'avatar_url' => 'http://p5z1781je.bkt.clouddn.com',
  'cover_bucket' => 'testscreenshot',
  'cover_url' => 'http://p5knudqvz.bkt.clouddn.com',
  'music_bucket' => 'musicpub',
  'music_url' => 'http://p3giatxrd.bkt.clouddn.com',
  'idcard_bucket' => 'testidcard',
  'idcard_url' => 'http://idcard.yixiu08.com',
  'original_bucket' => 'videoori',
  'public_bucket' => 'videopub',
  'public_url' => 'https://videopub.actuive.com',
  'other_bucket' => 'testheadimg',
  'other_url' => 'http://p5z1781je.bkt.clouddn.com',
  'sms_sign_name' => '小印象',
  'sms_register' => 'SMS_118965017',
  'sms_update_password' => 'SMS_141596106',
  'sms_binding_mobile' => 'SMS_133970435',
  'sms_set_pay_password' => 'SMS_141581044',
  'sms_unbind_third_account' => 'SMS_141615929',
  'sms_unbind_burse_account' => 'SMS_141596107',
  'sms_update_mobile' => 'SMS_141581043',
  'sms_update_pay_password' => 'SMS_141606040',
  'sms_code_login' => 'SMS_145598458',
  'private_bucket' => 'videopri1',
  'private_url' => 'https://pa1ooso5l.bkt.clouddn.com',
);