<?php

return array (
  'name' => '小印象',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'general/profile',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'upload' => 'Upload',
    'sms' => '短信',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'qiniu_access_key' => 'OUahOqyuJIzcOT_ImZl4tfg1MyH2X2mVl8Mwk6GF',
  'qiniu_secret_key' => '_iQedrZ1zSls6Fs0RmX94ZQ6QdAHekivaXO-eHKk',
  'avatar_bucket' => 'testheadimg',
  'avatar_url' => 'http://p5z1781je.bkt.clouddn.com',
  'cover_bucket' => 'testscreenshot',
  'cover_url' => 'http://p5knudqvz.bkt.clouddn.com',
  'music_bucket' => '',
  'music_url' => '',
  'idcard_bucket' => '',
  'idcard_url' => '',
  'original_bucket' => '',
  'public_bucket' => '',
  'public_url' => '',
  'other_bucket' => '',
  'other_url' => '',
  'sign_name' => '小印象',
  'sing' => 'SMS_118965017',
);